Remove truncate brew package
coreutils now includes this functionality.  Addresses Travis errors of
the form:

Error: Cannot install truncate because conflicting formulae are installed.
  coreutils: because both install `truncate` binaries

Please `brew unlink coreutils` before continuing.